create extension if not exists pgcrypto;

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text,
  phone text,
  name text,
  google_id text,
  stripe_customer_id text,
  avatar_url text,
  bio text,
  created_at timestamptz default now()
);

alter table public.users alter column email drop not null;
alter table public.users add column if not exists phone text;
alter table public.users add column if not exists avatar_url text;
alter table public.users add column if not exists bio text;
alter table public.users add column if not exists google_id text;
alter table public.users add column if not exists stripe_customer_id text;

create unique index if not exists users_email_key on public.users (email) where email is not null;
create unique index if not exists users_phone_key on public.users (phone) where phone is not null;
create unique index if not exists users_google_id_key on public.users (google_id) where google_id is not null;
create unique index if not exists users_stripe_customer_id_key on public.users (stripe_customer_id) where stripe_customer_id is not null;

create table if not exists public.instances (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade,
  ec2_instance_id text,
  public_ip text,
  status text default 'provisioning',
  model_provider text,
  model_name text,
  channel text default 'telegram',
  telegram_bot_token text,
  teams_app_id text,
  teams_app_password text,
  whatsapp_phone_id text,
  whatsapp_access_token text,
  llm_api_key text,
  gateway_token text,
  region text default 'ap-south-1',
  bot_id text,
  companion_name text,
  companion_role text,
  companion_color text,
  companion_avatar text,
  character_files jsonb,
  created_at timestamptz default now(),
  last_health_check timestamptz
);

alter table public.instances add column if not exists teams_app_id text;
alter table public.instances add column if not exists teams_app_password text;
alter table public.instances add column if not exists whatsapp_phone_id text;
alter table public.instances add column if not exists whatsapp_access_token text;
alter table public.instances add column if not exists bot_id text;
alter table public.instances add column if not exists companion_name text;
alter table public.instances add column if not exists companion_role text;
alter table public.instances add column if not exists companion_color text;
alter table public.instances add column if not exists companion_avatar text;
alter table public.instances add column if not exists character_files jsonb;

create index if not exists idx_instances_user_status on public.instances(user_id, status);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(id) on delete cascade,
  stripe_subscription_id text,
  status text,
  current_period_end timestamptz,
  created_at timestamptz default now()
);

create unique index if not exists subscriptions_stripe_subscription_id_key
  on public.subscriptions (stripe_subscription_id)
  where stripe_subscription_id is not null;

create table if not exists public.community_bots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  author_name text not null default 'Anonymous',
  author_email text,
  name text not null,
  bot_name text not null,
  description text default '',
  icon_url text,
  character_file text,
  soul_md text,
  bot_role text,
  color text,
  tools_config jsonb,
  category text default 'other',
  tags text[] default '{}',
  upvotes integer not null default 0,
  downvotes integer not null default 0,
  likes integer not null default 0,
  deploys integer not null default 0,
  fork_count integer not null default 0,
  forked_from bigint references public.community_bots(id) on delete set null,
  status text not null default 'published',
  created_at timestamptz default now()
);

create index if not exists idx_community_bots_status_created
  on public.community_bots(status, created_at desc);
create index if not exists idx_community_bots_user_status
  on public.community_bots(user_id, status);
create index if not exists idx_community_bots_category
  on public.community_bots(category);

create table if not exists public.community_votes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  bot_id bigint not null references public.community_bots(id) on delete cascade,
  vote_type text not null check (vote_type in ('up', 'down')),
  created_at timestamptz default now(),
  unique (user_id, bot_id)
);

create index if not exists idx_community_votes_bot_id on public.community_votes(bot_id);

create table if not exists public.bot_likes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  bot_id text not null,
  created_at timestamptz default now(),
  unique (user_id, bot_id)
);

create index if not exists idx_bot_likes_bot_id on public.bot_likes(bot_id);

create table if not exists public.companion_reviews (
  id uuid primary key default gen_random_uuid(),
  bot_id text not null,
  user_id uuid not null references public.users(id) on delete cascade,
  user_name text,
  user_avatar text,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text not null,
  created_at timestamptz default now()
);

create index if not exists idx_reviews_bot_id on public.companion_reviews(bot_id);
create index if not exists idx_reviews_created on public.companion_reviews(created_at desc);

create or replace function public.decrement_upvotes(row_id bigint)
returns void
language sql
as $$
  update public.community_bots
  set upvotes = greatest(coalesce(upvotes, 0) - 1, 0)
  where id = row_id;
$$;

create or replace function public.decrement_downvotes(row_id bigint)
returns void
language sql
as $$
  update public.community_bots
  set downvotes = greatest(coalesce(downvotes, 0) - 1, 0)
  where id = row_id;
$$;
